app/javascript/packs/application.js, app/javascript/stylesheets/application.scss, app/views/layouts/application.html.erb, config/webpack/environment.js, package.json, yarn.lock
Bootstrapのインストール
FontAwesomeのインストール
=> Bootstrap-Fontawesome_install

db/migrate/20221217041628_create_active_storage_tables.active_storage.rb, db/schema.rb
=> add ActiveStorage

app/views/layouts/application.html.erb
=> add header

app/controllers/application_controller.rb, app/controllers/public/registrations_controller.rb, app/models/customer.rb, app/views/public/registrations/new.html.erb
=> Customers sign up screen

app/controllers/public/sessions_controller.rb, app/views/public/registrations/new.html.erb, app/views/public/sessions/new.html.erb
=> add customer-sign_in-screen

app/views/layouts/application.html.erb
=> add header-color

app/controllers/application_controller.rb, app/views/public/registrations/new.html.erb
新規登録が上手くできなかったためコードを修正。
新規登録できるように改善できました。
=> fix customers-sign_up-screen

app/views/public/sessions/new.html.erb
=> fix customers-sign_in-screen

app/controllers/public/customers_controller.rb, app/views/public/customers/edit.html.erb, app/views/public/customers/show.html.erb, app/views/public/customers/unsubscribe.html.erb, app/views/public/orders/new.html.erb
○マイページ画面作成
○退会確認画面作成
○会員情報編集画面作成
完了しました。
=> Edit other screen

app/controllers/admin/items_controller.rb, app/views/admin/items/edit.html.erb, app/views/admin/items/index.html.erb, app/views/admin/items/new.html.erb, app/views/admin/items/show.html.erb, config/routes.rb
=> Admin items show

app/controllers/public/addresses_controller.rb, app/views/public/addresses/edit.html.erb, app/views/public/addresses/index.html.erb, db/schema.rb
=> Address screen

app/controllers/public/items_controller.rb, app/views/layouts/application.html.erb, app/views/public/items/show.html.erb
=> fix public-items-show

Gemfile, Gemfile.lock, app/controllers/admin/items_controller.rb, app/views/admin/genres/edit.html.erb, app/views/admin/genres/index.html.erb, app/views/admin/items/edit.html.erb, app/views/admin/items/index.html.erb, app/views/admin/items/new.html.erb, app/views/admin/items/show.html.erb, app/views/layouts/application.html.erb
adminのitemsの詳細画面、一覧画面、編集画面とgenresの一覧画面、編集画面を修正しました。
=> Genres index

app/controllers/public/cart_items_controller.rb, app/models/cart_item.rb, app/views/public/cart_items/index.html.erb, config/routes.rb
=> add cart_items-screen

app/controllers/public/orders_controller.rb, app/views/public/orders/confirm.html.erb, app/views/public/orders/new.html.erb, config/routes.rb
=> Orders info input screen

app/controllers/public/orders_controller.rb, app/views/public/orders/confirm.html.erb, app/views/public/orders/index.html.erb, app/views/public/orders/show.html.erb, config/routes.rb, db/migrate/20221216015716_create_order_details.rb, db/schema.rb
=> Order detail

app/controllers/admin/order_details_controller.rb, app/controllers/admin/orders_controller.rb, app/views/admin/homes/top.html.erb, app/views/admin/orders/show.html.erb
=> add admin_orders-screen

app/controllers/application_controller.rb
=> Add admin-validation

app/controllers/public/addresses_controller.rb, app/controllers/public/cart_items_controller.rb, app/controllers/public/customers_controller.rb, app/controllers/public/homes_controller.rb, app/controllers/public/items_controller.rb, app/controllers/public/orders_controller.rb
=> public側バリデーション設定

app/views/admin/orders/show.html.erb
=> fix order-screen
